export var carouselIcons = [
    'access point.png',
    'firewalls.png',
    'gateway.jpg',
    'load balancer.png',
    'network interferance module.png',
    'network module.jpg',
    'network security.png',
    'power supply.png',
    'racks.png',
    'router.jpg',
    'router.png',
    'server accessory.png',
    'server and storage.png',
    'servers.png',
    'software accessory.jpg',
    'software service and support.jpg',
    'storge server.png',
    'switch.png',
    'unified communication and collaboration equipment.png',
    'voip phone and equipment.png',
    'wireless bridge and extenders.png',
    'wireless controller.png',
    'wlan wifi antenna.png'
]